import React, { useState } from 'react';
import { 
  Page, 
  Card, 
  Layout,
  Tabs,
  Box,
  Banner,
  Select,
  Button,
  BlockStack,
  InlineStack,
} from '@cin7/polaris-adapter';
import Editor from '@monaco-editor/react';
import { examples } from '../examples';
import PreviewPanel from '../components/PreviewPanel';

export default function EditorPage() {
  const [selectedExample, setSelectedExample] = useState('product-card');
  const [code, setCode] = useState(examples[selectedExample].code);
  const [selectedTab, setSelectedTab] = useState(0);
  const [showPreview, setShowPreview] = useState(true);

  const exampleOptions = Object.entries(examples).map(([key, example]) => ({
    label: example.name,
    value: key,
  }));

  const handleExampleChange = (value: string) => {
    setSelectedExample(value);
    setCode(examples[value].code);
  };

  const tabs = [
    {
      id: 'dsl',
      content: 'DSL Code',
      panelID: 'dsl-panel',
    },
    {
      id: 'compiled',
      content: 'Compiled Output',
      panelID: 'compiled-panel',
    },
  ];

  return (
    <Page 
      title="Cin7 DSL Editor"
      primaryAction={{
        content: showPreview ? 'Hide Preview' : 'Show Preview',
        onAction: () => setShowPreview(!showPreview),
      }}
    >
      <Layout>
        <Layout.Section>
          <Banner
            title="Interactive DSL Editor"
            tone="info"
            onDismiss={() => {}}
          >
            <p>
              Write Cin7 DSL code on the left and see the live preview on the right. 
              The DSL compiler is simulated for demonstration purposes.
            </p>
          </Banner>
        </Layout.Section>

        <Layout.Section>
          <Card padding="0">
            <Box padding="400" borderBlockEndWidth="025" borderColor="border">
              <InlineStack gap="400" align="space-between">
                <Select
                  label="Example"
                  labelInline
                  options={exampleOptions}
                  value={selectedExample}
                  onChange={handleExampleChange}
                />
                <Button
                  onClick={() => setCode(examples[selectedExample].code)}
                  plain
                >
                  Reset Code
                </Button>
              </InlineStack>
            </Box>

            <div style={{ display: 'flex', height: '600px' }}>
              <div style={{ flex: showPreview ? '1' : '1 0 100%', display: 'flex', flexDirection: 'column' }}>
                <Tabs tabs={tabs} selected={selectedTab} onSelect={setSelectedTab}>
                  <Box padding="0" background="bg-surface-secondary" minHeight="100%">
                    {selectedTab === 0 ? (
                      <Editor
                        height="550px"
                        defaultLanguage="typescript"
                        value={code}
                        onChange={(value) => setCode(value || '')}
                        theme="vs-light"
                        options={{
                          minimap: { enabled: false },
                          fontSize: 14,
                          lineNumbers: 'on',
                          scrollBeyondLastLine: false,
                          wordWrap: 'on',
                          wrappingIndent: 'indent',
                        }}
                      />
                    ) : (
                      <Box padding="400">
                        <pre style={{ margin: 0, fontSize: '14px' }}>
                          {generateCompiledCode(code)}
                        </pre>
                      </Box>
                    )}
                  </Box>
                </Tabs>
              </div>

              {showPreview && (
                <div style={{ 
                  flex: '1', 
                  borderLeft: '1px solid var(--p-color-border)',
                  overflow: 'auto'
                }}>
                  <PreviewPanel 
                    code={code} 
                    example={examples[selectedExample]}
                  />
                </div>
              )}
            </div>
          </Card>
        </Layout.Section>
      </Layout>
    </Page>
  );
}

function generateCompiledCode(dslCode: string): string {
  // Simple simulation of DSL compilation
  const lines = dslCode.split('\n');
  let output = '// Generated by Cin7 DSL Compiler\n\n';
  
  // Extract component name
  const componentMatch = dslCode.match(/component\s+(\w+)/);
  if (componentMatch) {
    output += `import React from 'react';\n`;
    output += `import { createElement } from '@cin7/vanilla-js';\n\n`;
    output += `export function ${componentMatch[1]}(props) {\n`;
    
    // Extract state
    const stateMatch = dslCode.match(/state\s*{([^}]+)}/s);
    if (stateMatch) {
      const stateVars = stateMatch[1].trim().split('\n').filter(line => line.trim());
      stateVars.forEach(stateVar => {
        const [name, defaultValue] = stateVar.split('=').map(s => s.trim());
        const [varName] = name.split(':').map(s => s.trim());
        output += `  const [${varName}, set${varName.charAt(0).toUpperCase() + varName.slice(1)}] = React.useState(${defaultValue || 'null'});\n`;
      });
    }
    
    output += '\n  return (\n    <div>/* Component implementation */</div>\n  );\n}\n';
  }
  
  return output;
}